runtime: python38
entrypoint: uwsgi --ini server/uwsgi-gae.ini --http :$PORT

instance_class: F2

automatic_scaling:
  min_instances: 1
  max_instances: 1
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 10

handlers:
  - url: /static
    static_dir: static/

  - url: /.*
    script: auto
