# Generated by Django 3.1 on 2020-09-24 18:03

import DomePortfolio.lib.storage.gcp_storage
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', imagekit.models.fields.ProcessedImageField(null=True, storage=DomePortfolio.lib.storage.gcp_storage.ImageStorage(), upload_to='')),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Section',
            },
        ),
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_desktop', models.FileField(help_text='Video displayed on desktop devices (16:9), should be max. 25MB per minute', null=True, storage=DomePortfolio.lib.storage.gcp_storage.VideoStorage(), upload_to='')),
                ('video_mobile', models.FileField(help_text='Video displayed on mobile devices (9:18), should be max. 15MB per minute', null=True, storage=DomePortfolio.lib.storage.gcp_storage.VideoStorage(), upload_to='')),
            ],
            options={
                'verbose_name': 'Home Section',
                'verbose_name_plural': 'Home Section',
            },
        ),
        migrations.CreateModel(
            name='VitaParagraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_field', models.PositiveSmallIntegerField(default=0)),
                ('text', models.CharField(max_length=255)),
                ('year', models.PositiveSmallIntegerField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vita', to='content.aboutsection')),
            ],
            options={
                'ordering': ['order_field'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AboutParagraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_field', models.PositiveSmallIntegerField(default=0)),
                ('text', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about', to='content.aboutsection')),
            ],
            options={
                'ordering': ['order_field'],
                'abstract': False,
            },
        ),
    ]
