# Generated by Django 3.1 on 2020-08-17 15:03

import DomePortfolio.lib.storage.gcp_storage.storage
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('thumbnail', imagekit.models.fields.ProcessedImageField(storage=DomePortfolio.lib.storage.gcp_storage.storage.GCPStorage(), upload_to='')),
                ('year', models.PositiveSmallIntegerField(default=2020)),
                ('client', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('video', models.URLField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.categorytree')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('thumbnail', imagekit.models.fields.ProcessedImageField(storage=DomePortfolio.lib.storage.gcp_storage.storage.GCPStorage(), upload_to='')),
                ('year', models.PositiveSmallIntegerField(default=2020)),
                ('client', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.categorytree')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_field', models.PositiveSmallIntegerField(default=0)),
                ('image', imagekit.models.fields.ProcessedImageField(storage=DomePortfolio.lib.storage.gcp_storage.storage.GCPStorage(), upload_to='')),
                ('parent_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.imageitem')),
            ],
            options={
                'ordering': ['order_field'],
                'abstract': False,
            },
        ),
    ]
