# Generated by Django 3.1 on 2020-09-19 09:12

from django.db import migrations, models
import djmoney.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed', models.BooleanField(default=False)),
                ('related_paypal_order', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('ordered_on', models.DateTimeField(null=True)),
                ('customer_email', models.EmailField(max_length=254, null=True)),
                ('customer_id', models.CharField(max_length=100, null=True)),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar')], default='EUR', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=4, default_currency='EUR', max_digits=19)),
                ('purchased_with_sale', models.PositiveSmallIntegerField(default=0)),
                ('product_downloads_remaining', models.PositiveSmallIntegerField(null=True)),
                ('download_expires_on', models.DateTimeField(null=True)),
                ('product_download', models.URLField(null=True)),
            ],
        ),
    ]
