# Generated by Django 3.1 on 2020-09-17 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_defaults'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorytree',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
