# Generated by Django 3.1 on 2020-08-25 22:55

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='amount_paid',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='amount_paid_currency',
            new_name='amount_currency',
        ),
        migrations.AddField(
            model_name='order',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='download_expires_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_by',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_downloads_remaining',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
