# Generated by Django 3.1 on 2020-08-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_product_download'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered_by',
            new_name='customer_email',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
