# Generated by Django 3.1 on 2020-08-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200825_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='related_paypal_order',
            field=models.CharField(default=123456789, max_length=100),
            preserve_default=False,
        ),
    ]
